# Generated by Django 5.1.3 on 2024-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("product", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=200)),
                ("summary", models.TextField()),
            ],
        ),
    ]
