# Generated by Django 5.1.3 on 2024-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="address",
            field=models.CharField(default="Default Address", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="name",
            field=models.CharField(default="name", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="phone",
            field=models.CharField(default="phone", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="price",
            field=models.CharField(default="price", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total",
            field=models.CharField(default="total", max_length=78),
        ),
    ]
