# Generated by Django 5.1.3 on 2024-12-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_invoice_address_invoice_description_invoice_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="image",
            field=models.ImageField(default="image", upload_to="image/"),
        ),
    ]

